general:
  mq: rabbitmq

rabbitmq:
  host: localhost
  port: 5672
  #user: guest
  #password: guest

redis:
  cache_ttl: 86400              # 1 day
  host: localhost
  port: 6379
  db: 2


logging:
  loglevel: 'DEBUG'             # optional, the actual loglevel will be set on the individual handlers, default=DEBUG
  facility: 'yellowsub'         # optional
  handlers:
    - handler:
        type: 'TimedRotatingFileHandler'
        output: '/var/log/yellowsub.INFO.log'
        loglevel: 'INFO'
    - handler:
        type: 'TimedRotatingFileHandler'
        output: '/var/log/yellowsub.WARN.log'
        loglevel: 'WARN'           # optional

processors:
  # list of settings for each individual processor instance
  sample-gethostbyname:
    dns_recursor: "8.8.8.8"
    validate_msg: True
  mispattributesearcher:
    misp_uri: "https://192.168.5.108/"
    misp_api_key: ""
    logging: # override any of the settings of the global logger here if needed
      loglevel: 'DEBUG'
      handlers:
        - handler:
            type: 'TimedRotatingFileHandler'
            output: '/var/log/yellowsub.mispattributesearcher.INFO.log'
            loglevel: 'INFO'
        - handler:
            type: 'TimedRotatingFileHandler'
            output: '/var/log/yellowsub.mispattributesearcher.WARN.log'
            loglevel: 'WARN'


workflows:
  - { input_queue: <name of queue> , processor: <id of processor> , output_exchange: <id of output exchange> }
