workflow:
  description: "my workflow"
  author: "kaplale"
  flow:
  # simple linear example: get urls from somewhere (configured in the url_collector.yml) and do parallel lookups in safebrowsing, finally write the enriched results to a file.
  - { proc_id: "url_collector", to: ["ex1", "ex2"] }
  - { proc_id: "is_url_on_safebrowsing", from: "ex1.q1.sb", to: ["ex15"], paralellism: 3 }
  - { proc_id: "output_file_writer", from: "ex15.q"}

workflow2:
  description: "my workflow 2"
  author: "kaplale"
  flow:
  # simple linear example: get urls from somewhere (configured in the url_collector.yml) and do parallel lookups in safebrowsing, finally write the enriched results to a file.
  - { proc_id: "url_collector", to: ["ex1", "ex2"] }
  - { proc_id: "is_url_on_safebrowsing", from: "ex1.q1.sb", to: ["ex15"], paralellism: 3 }
  - { proc_id: "output_file_writer", from: "ex15.q"}
