workflow:
  description: "my workflow"
  author: "kaplale"
  flow:
  # simple linear example: get urls from somewhere (configured in the url_collector.yml) and do parallel lookups in safebrowsing, finally write the enriched results to a file.
  - { processor: "url_collector", to: "ex1" }
  - { processor: "is_url_on_safebrowsing", from: "ex1", to: "ex15", paralellism: 3 }
  - { processor: "output_file_writer", from: "ex15"}

workflow2:
  description: "my workflow 2"
  author: "kaplale"
  flow:
  # simple linear example: get urls from somewhere (configured in the url_collector.yml) and do parallel lookups in safebrowsing, finally write the enriched results to a file.
  - { processor: "url_collector", to: "ex100" }
  - { processor: "is_url_on_safebrowsing", from: "ex100", to: "ex150", paralellism: 3 }
  - { processor: "output_file_writer", from: "ex150"}