- name: Codecov
  # You may pin to the exact commit or the version.
  # uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b
  uses: codecov/codecov-action@v2.1.0
  with:
    # Repository upload token - get it from codecov.io. Required only for private repositories
    token: 93abcce8-80b5-4261-a181-c6e1aee00a03
    # Comma-separated list of files to upload
    # files: # optional
    # Directory to search for coverage reports.
    # directory: # optional
    # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
    # flags: # optional
    # The commit SHA of the parent for which you are uploading coverage. If not present, the parent will be determined using the API of your repository provider.  When using the repository providers API, the parent is determined via finding the closest ancestor to the commit.
    # commit_parent: # optional
    # Don't upload files to Codecov
    dry_run:  True # optional
    # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
    env_vars: PYTHON_PATH=lib
    # Specify whether or not CI build should fail if Codecov runs into an error during upload
    fail_ci_if_error: True # optional
    # Path to coverage file to upload
    #file: # optional
    # Comma-separated list, see the README for options and their usage
    #functionalities: # optional
    # Move discovered coverage reports to the trash
    #move_coverage_to_trash: # optional
    # User defined upload name. Visible in Codecov UI
    #name: # optional
    # Specify the branch name
    #override_branch: # optional
    # Specify the build number
    verbose: True # optional
