# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: unittests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest nose pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt install redis
        sudo service redis-server start
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --ignore=E251,E225,E741,E501,W605,W391 --exclude=.git,venv,contrib,lib/python3.8 --count --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --ignore=E251,E225,E741,E501,W605,W391 --exclude=.git,venv,contrib,lib/python3.8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        export PYTHONPATH=lib ; export ROOTDIR=$(pwd); pytest --cov=./ tests
